export const SET_TV_SHOWS = "SET_TV_SHOWS"
export const SET_TV_SHOW_SUGGESTION = "SET_TV_SHOW_SUGGESTION"
export const SET_SELECTED_TV_SHOW = "SET_SELECTED_TV_SHOW"
export const SET_CURRENT_EPISODE = "SET_CURRENT_EPISODE"
